create order for admin and few example method for user
MaxIsmansky/rapidcrm pull request #7
Opened 2022-12-04 18:12 UTC by Kukisvum

2022-12-04 21:03 UTC, MaxIsmansky requested changes
Оставил комменты по цене, остальное работает?

2022-12-04 21:03 UTC, MaxIsmansky commented on src/main/java/com/rapidsystems/soft/project/model/plate/ProductPlate.java
> +    private Double price;
Деньги в Double? Храни в копейках интах и потом если нужно переводи в рубли, в даблах даже просуммировать без появления 0.000000000000...n нормально не получится

2022-12-04 21:03 UTC, MaxIsmansky commented on src/main/java/com/rapidsystems/soft/project/model/order/Order.java
> +    private Double price;
Те же деньги в Double...

2022-12-05 17:12 UTC, Kukisvum commented on src/main/java/com/rapidsystems/soft/project/model/order/Order.java
> +    private Double price;
Готово)

2022-12-14 13:12 UTC, MaxIsmansky approved these changes

2022-12-14 13:23 UTC, merged